<?php

namespace OC\PlatformBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ApplicationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ApplicationRepository extends EntityRepository
{
    /*
        * But : Récupérer les X dernières candidatures avec leur annonce associée
        */
    /**
     * @name getApplicationsWithAdvert
     * @param int $limit
     * @return array, jeux de résultat
     */
    public function getApplicationsWithAdvert($limit)
    {
        $qb = $this->createQueryBuilder("a");
        // On fait la jointure avec l'entité Advert avec pour alias « adv »
        $qb
            ->innerJoin("a.advert", "adv")
            ->addSelect("adv");
        // Puis on ne retourne que le nombre de résultats demandé par $limit
        $qb->setMaxResults($limit);

        // Enfin on retourne le résultat
        return $qb->getQuery()->getResult();
    }

    /**
     * @param string $ip
     * @param integer $seconds
     * @return bool
     */
    public function isFlood($ip, $seconds)
    {
        return (bool) $this->createQueryBuilder('a')
            ->select('COUNT(a)')
            ->where("a.date >= :date")
            ->setParameter('date', new \DateTime($seconds. ' seconds ago'))
            ->getQuery()
            ->getSingleScalarResult();
    }
}

